- index.js
> [40] Add event bridge section

- src/index.js
With this PR, Lambda function configurations are retrieved and currently only runtime is shown in the Lambda functions box under the new 3rd `runtime` column.
As an optimization, Lambda function configurations are not retrieved at every interval but when there is an update. In case of update in the Lambda function resources, instead of getting updated function configurations one by one individually, we are getting all the functions' configurations in batch even though there will be unrelated ones with the stack. Because this should result with less API calls in most cases. 
The downside of this approach is that if the Lambda function configurations are updated outside of stack (for ex. manually by AWS console), it will not be detected by smart refresh mechanism. But I think this is not …
> Retrieve Lambda functions' runtime configurations to show in the Lambda functions box

- src/components/durationBarChart.js
- src/index.js
- src/modals/helpModal.js
- src/modals/lambdaStatisticsModal.js
> [188] add lambda statistics window

- package.json
- src/index.js
- src/services/serverless.js
Resolves #53. 
This might still miss some corner cases that I'm not aware of, but at least with my testing this seems to be working.
> Read stackName & region from serverless.y[a]ml when using SLS

- package.json
- src/index.js
- src/services/serverless.js
Reverts Theodo-UK/sls-dev-tools#100
> Artoliukkonen master

- src/components/interactiveList.js
- src/modals/eventInjectionModal.js
- src/modals/eventRegistryModal.js
- src/modals/eventSchemaModal.js
- src/modals/helpModal.js
Used new components classes in all modals.
Added additional component for lists
> Refactor modals

- README.md
- src/index.js
- src/modals/helpModal.js
- src/services/invoke.js
> First attempt an basic lambda function invoke

- src/components/lambdaDeploymentsTable.js
- src/index.js
- src/modals/lambdaStatisticsModal.js
> [231] Deployment History

- .all-contributorsrc
- README.md
Reverts Theodo-UK/sls-dev-tools#132
> Revert "docs: add luce as a contributor"

- .all-contributorsrc
- README.md
Reverts Theodo-UK/sls-dev-tools#133
> Revert "Revert "docs: add luce as a contributor""

- src/index.js
- src/modals/clargsWizardModal.js
Currently opens the modal wizard, however selecting a region will cause the program to error due to the Map component.
> Create modal wizard component, open when region not supplied

- package.json
- src/index.js
- src/utils/updateNotifier.js
- yarn.lock
Basic update notifier, showing if there's an update available when the tool is quit. 
Kinda fixes #153 , but could be improved to do a lot more as mentioned in that task. But feel free to use this as a base :)
> Basic update notifier

- src/components/resourceTable.js
- src/modals/relayModal.js
> Create relay modal

- src/components/resourceTable.js
- src/modals/errorModal.js
- src/modals/relayModal.js
> Display error modal if lambda does not have node runtime

- src/components/loader.js
- src/modals/relayModal.js
> Display loading component on Relay setup

- src/index.js
- src/modals/disableRelayModal.js
- src/modals/relayModal.js
Prompts the user once, then quits as normal
> Add warning on quit if Relay layer enabled

- src/index.js
- src/utils/updateNotifier.js
Notifications will still only be sent a maximum of once per day
> Fix update notifier

- README.md
- docs/README.md
- package.json
- src/index.js
- src/services/invoke.js
- src/services/processEventLogs.js
- yarn.lock
Reverts Theodo-UK/sls-dev-tools#220
> Revert "Feature/58 push notifications"

- src/CLIMain.js
- src/services/awsCredentials.js
- src/services/index.js
Reverts Theodo-UK/sls-dev-tools#237
> Revert "Refactor MFA entry to be used with different token functions"

- src/components/resourceTable.js
- src/index.js
- src/modals/disableRelayWarningModal.js
- src/modals/index.js
Modal displayed when selecting lambda for a 3rd time
Modal displayed when trying to quit tool with relay enabled moved to displayRelayWarningModal.js
> Display disableRelayModal on selecting relay enabled lambda
